Llifo.Overlay/Models/BoardItem.cs
namespace Llifo.Overlay.Models
{
    public class BoardItem
    {
        /// <summary>
        /// Name of the underlying asset.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Web path of the underlying asset.
        /// </summary>
        public string Path { get; set; }
    }
}

Llifo.Overlay/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Llifo.Overlay.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Llifo.Overlay/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Llifo.Overlay.Hubs;
using Llifo.Overlay.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;

namespace Llifo.Overlay.Pages
{
    /// <summary>
    /// Page Model of the /Index aka Root file.
    /// 
    /// It provides a list of board items and the
    /// possiblity to broadcast a change in the selection
    /// of an item via SignalR.
    /// </summary>
    public class IndexModel : PageModel
    {
        #region Public properties

        /// <summary>
        /// Underlying list of board items.
        /// </summary>
        public List<BoardItem> BoardItems;

        #endregion

        #region Private members

        /// <summary>
        /// Underlying hosting information context.
        /// </summary>
        private readonly IHostingEnvironment environment;

        /// <summary>
        /// Underlying board hub context.
        /// </summary>
        private readonly IHubContext<BoardHub> hubContext;

        #endregion

        /// <summary>
        /// Initializer.
        /// 
        /// </summary>
        /// <param name="environment">
        /// Underlying hosting environment that is set via dependency injection.
        /// </param>
        /// <param name="hubContext">
        /// Underlying SignalR hub that is set via dependency injection.
        /// </param>
        public IndexModel(IHostingEnvironment environment, IHubContext<BoardHub> hubContext)
        {
            this.environment = environment;
            this.hubContext = hubContext;
        }

        #region Http Event handler

        /// <summary>
        /// Gets called on Http GET requests.
        /// 
        /// Will setup `BoardItems` member.
        /// </summary>
        public void OnGet()
        {
            // 1. Get file names from web root path + "/content" folder.
            //      In most cases this should be "wwwroot/content".
            //
            // 2. Remove the absolute path including the wwwroot path.
            //
            // 3. Map these paths into `BoardItem` object.
            //
            // 3. The page will now use this member to render the list of 
            //      board items.
            BoardItems = Directory
                .GetFiles(Path.Combine(environment.WebRootPath, "content"))
                .Select(path => path.Replace(environment.WebRootPath, string.Empty))
                .Select(path => new BoardItem
                {
                    Name = Path.GetFileName(path),
                    Path = path
                })
                .ToList();
        }

        /// <summary>
        /// Handles Http-Get action for showing a asset on 
        /// on the overlay view.
        /// </summary>
        /// <param name="id">Web path of the selected board item.</param>
        public async Task<IActionResult> OnGetShowAsync(string? id)
        {
            // Ensure a path is given.
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToPage("Index");
            }

            // Post a SignalR message. In this example, the `StreamOverlay.cshtml`
            // will listen to this broadcast via a simple JavaScript event handdler
            // which is located in `/js/streamOverlay.js`.
            await hubContext.Clients.All.SendAsync("BoardItemChanged", id);
            return RedirectToPage("Index");
        }

        #endregion
    }
}

Llifo.Overlay/Pages/StreamOverlay.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Llifo.Overlay.Pages
{
    public class StreamOverlayModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Llifo.Overlay/Pages/Index.cshtml
@page
@model IndexModel
<!-- Render static header -->
<div class="header-container">
    <span class="ms-fontSize-28 ms-fontColor-purple ms-fontWeight-semibold">
        Llifo.Overlay
    </span>
    <span class="ms-fontSize-12 ms-fontColor-gray140">
        ASP.NET Core SignalR Core Demo.
    </span>
</div>

@if (Model.BoardItems.Count == 0)
{
    <p>No board items available.</p>
}
else
{
    <!-- Open Stream overlay link -->
    <div>
        <a href="StreamOverlay" target="_blank">Open </a>
        <span class="ms-fontColor-gray140">Stream overlay in popup</span>
    </div>

    <!-- List of items -->
    <div class="boarditems-container">
        @foreach (var item in Model.BoardItems)
        {
            <a asp-page="./Index" asp-page-handler="show" asp-route-id="@item.Path" title="Show">
                <div class="boarditem-container">
                    <img src="@item.Path" /><br />
                    <span style="vertical-align:bottom">@Html.DisplayFor(modelItem => item.Name)</span>
                </div>
            </a>
        }
    </div>
}

Llifo.Overlay/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Render meta information region -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Title of page - in this case application -->
    <title>Llifo.Overlay</title>

    <!-- Render Stylesheet import region -->
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.0.0/css/fabric.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body class="ms-Fabric" dir="ltr">
    <!-- Render Body region-->
    @RenderBody()

    <!-- Render JavaScript import region -->
    @RenderSection("Scripts", required: false)
</body>
</html>

Llifo.Overlay/Pages/StreamOverlay.cshtml
@page
@model Llifo.Overlay.Pages.StreamOverlayModel
@{
    Layout = null;
}

<html>
<body style="margin: 0px; padding: 0px;">
    <!-- 
        Image place holder that will be filled by the
        streamoverlay.js event handler
    -->
    <img id="boardImage" src=""  style="max-width:100%; max-height: 100%;" />

    <!-- Embed SignalR JavaScript -->
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/streamOverlay.js"></script>
</body>
</html>